<?xml version="1.0"?>
<robot name="biibiii"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <gazebo reference="base_link">
        <material>Gazebo/YellowGlow </material>
    </gazebo>

    <gazebo reference="left_wheel_link">
        <material>Gazebo/WhiteGlow </material>
    </gazebo>

    <gazebo reference="right_wheel_link">
        <material>Gazebo/GreenGlow  </material>
    </gazebo>

    <gazebo reference="front_caster_link">
        <material>Gazebo/GreenGlow </material>
    </gazebo>

    <gazebo reference="back_caster_link">
        <material>Gazebo/WhiteGlow </material>
    </gazebo>

    <gazebo reference="imu_link">
        <sensor type="imu" name="imu">
            <always_on>true</always_on>
            <visualize>true</visualize>
        </sensor>
        <material>Gazebo/FlatBlack</material>
    </gazebo>

    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <!-- <legacyMode>false</legacyMode> -->

            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <odometrySource>world</odometrySource>
            <publishOdomTF>true</publishOdomTF>
            <robotBaseFrame>base_footprint</robotBaseFrame>
            <publishWheelTF>false</publishWheelTF>
            <updateRate>20</updateRate>
            <leftJoint>base_to_left_wheel_joint</leftJoint>
            <rightJoint>base_to_right_wheel_joint</rightJoint>
            <!-- <wheelSeparation>0.6</wheelSeparation> -->
            <wheelSeparation>${base_width}</wheelSeparation>

            <publishWheelJointState>false</publishWheelJointState>
            <publishTf>true</publishTf>
            <!-- <wheelDiameter>0.15</wheelDiameter> -->
            <wheelDiameter>${wheel_radius*2}</wheelDiameter>
            <wheelAcceleration>1</wheelAcceleration>
            <wheelTorque>10</wheelTorque>
            <rosDebugLevel>na</rosDebugLevel>
        </plugin>
    </gazebo>


    <gazebo reference="base_scan_link">
        <material>Gazebo/WhiteGlow </material>
        <!-- <turnGravityOff>true</turnGravityOff> -->
        <sensor type="ray" name="base_scan_link">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>5</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>0</min_angle>
                        <max_angle>6.28319</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>40</max>
                    <resolution>0.015</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so">
                <topicName>scan</topicName>
                <frameName>base_scan_link</frameName>
                <alwaysOn>true</alwaysOn>
            </plugin>
        </sensor>
    </gazebo>

    <gazebo>
        <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
            <alwaysOn>true</alwaysOn>
            <bodyName>imu_link</bodyName>
            <frameName>imu_link</frameName>
            <topicName>imu</topicName>
            <serviceName>imu_service</serviceName>
            <gaussianNoise>0.0</gaussianNoise>
            <updateRate>0</updateRate>
            <imu>
                <noise>
                    <type>gaussian</type>
                    <rate>
                        <mean>0.0</mean>
                        <stddev>2e-4</stddev>
                        <bias_mean>0.0000075</bias_mean>
                        <bias_stddev>0.0000008</bias_stddev>
                    </rate>
                    <accel>
                        <mean>0.0</mean>
                        <stddev>1.7e-2</stddev>
                        <bias_mean>0.1</bias_mean>
                        <bias_stddev>0.001</bias_stddev>
                    </accel>
                </noise>
            </imu>
        </plugin>
    </gazebo>

    <!-- <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        </plugin>
    </gazebo> -->

    <gazebo reference="camera_rgb_frame">
        <material>Gazebo/GreenGlow </material>
        <sensor type="depth" name="realsense_R200">
            <always_on>true</always_on>
            <visualize>true</visualize>
            <camera>
                <horizontal_fov>1.3439</horizontal_fov>
                <image>
                    <width>1920</width>
                    <height>1080</height>
                    <!-- <format>R16</format> -->
                    <format>R8G8B8</format>
                </image>
                <depth_camera></depth_camera>
                <clip>
                    <near>0.03</near>
                    <far>100</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <baseline>0.2</baseline>
                <alwaysOn>true</alwaysOn>
                <updateRate>30.0</updateRate>
                <cameraName>camera</cameraName>
                <frameName>camera_rgb_optical_frame</frameName>
                <imageTopicName>rgb/image_raw</imageTopicName>
                <depthImageTopicName>depth/image_raw</depthImageTopicName>
                <pointCloudTopicName>depth/points</pointCloudTopicName>
                <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
                <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
                <pointCloudCutoff>0.4</pointCloudCutoff>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
                <CxPrime>0.0</CxPrime>
                <Cx>0.0</Cx>
                <Cy>0.0</Cy>
                <focalLength>0</focalLength>
                <hackBaseline>0</hackBaseline>
            </plugin>
        </sensor>
    </gazebo>

</robot>