<?xml version="1.0"?>
<robot name="biibiii" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Include the urdf/xacro file -->
    <xacro:include filename="$(find biibiii_description)/urdf/properties.xacro" />
    <xacro:include filename="$(find biibiii_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find biibiii_description)/urdf/robot.gazebo.xacro" />

    <!-- Robot Base footprint-->
    <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${base_height/2+wheel_zoff}" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- Robot base link-->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
            <material name="FFF6CE" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="1" w="${base_width}" d="${base_length}" h="${base_height}" />
    </link>

    <joint name="base_to_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-wheel_xoff} ${(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="left_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="white" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}" />
    </link>

    <joint name="base_to_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${(-wheel_xoff)} ${-(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="right_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="669966" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}" />
    </link>


    <!-- <joint name="base_to_caster_joint" type="fixed"> -->
    <joint name="base_to_front_caster_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_caster_link"/>
        <origin xyz="${-base_length/2} 0 ${-wheel_zoff}" rpy="0 0 0"/>
        <!-- <origin xyz="${(-base_length/4)} 0 ${-(base_height/2)}" rpy="0 0 0"/> -->
        <!-- <origin xyz="${(wheel_xoff+base_length/4)} 0.0 ${-(base_height/2)}" rpy="0 0 0"/> -->
        <axis xyz="0 1 0"/>
    </joint>

    <!-- Caster Wheel -->
    <link name="front_caster_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="669966" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>

        <xacro:sphere_inertia m="0.1" r="${caster_radius}"/>
    </link>

        <joint name="base_to_back_caster_joint" type="continuous">
        <parent link="base_link"/>
        <child link="back_caster_link"/>
        <origin xyz="${base_length/2} 0 ${-wheel_zoff}" rpy="0 0 0"/>
        <!-- <origin xyz="${(-base_length/4)} 0 ${-(base_height/2)}" rpy="0 0 0"/> -->
        <!-- <origin xyz="${(wheel_xoff+base_length/4)} 0.0 ${-(base_height/2)}" rpy="0 0 0"/> -->
        <axis xyz="0 1 0"/>
    </joint>

    <!-- Caster Wheel -->
    <link name="back_caster_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="white" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>

        <xacro:sphere_inertia m="0.1" r="${caster_radius}"/>
    </link>


    <joint name="base_to_scan_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_scan_link"/>
        <origin xyz="0 0 ${(base_height/2 + lidar_height/4)}" rpy="0 0 0"/>        
        <axis xyz="0 0 1"/>
        <!-- <limit lower="${-pi}" upper="${pi}" effort="14.27" velocity="0.5"/> -->
    </joint>


    <link name="base_scan_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_radius}"/>
            </geometry>
            <material name="white" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="0.007853" r="${lidar_radius}" h="${lidar_height}" />
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>
    <link name="imu_link" />

    <joint name="camera_joint" type="fixed">
        <origin xyz="${base_width/2-camera_height/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="base_camera_link"/>
        <axis xyz="0.0 0.0 0.0"/>
    </joint>

    <link name="base_camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0.0 1.57"/>
            <geometry>
                <box size="${camera_width} ${camera_length} ${camera_height}"/>
            </geometry>
            <material name="white" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_width} ${camera_length} ${camera_height}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="0.001" w="${camera_width}" d="${camera_length}" h="${camera_height}" />
    </link>


    <joint name="camera_rgb_joint" type="fixed">
        <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
        <parent link="base_camera_link"/>
        <child link="camera_rgb_frame"/>
    </joint>
    <link name="camera_rgb_frame"/>

    <joint name="camera_rgb_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="camera_rgb_frame"/>
        <child link="camera_rgb_optical_frame"/>
    </joint>
    <link name="camera_rgb_optical_frame"/>

    <joint name="camera_depth_joint" type="fixed">
        <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
        <parent link="base_camera_link"/>
        <child link="camera_depth_frame"/>
    </joint>
    <link name="camera_depth_frame"/>

    <joint name="camera_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="camera_depth_frame"/>
        <child link="camera_depth_optical_frame"/>
    </joint>
    <link name="camera_depth_optical_frame"/>

</robot>