global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: true

#   plugins:
#   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
#   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
#   - {name: static_layer, type: "costmap_2d::StaticLayer"}

# global_costmap:
#   global_costmap:
#     ros__parameters:
#       footprint_padding: 0.03
#       update_frequency: 10.0
#       publish_frequency: 10.0
#       global_frame: map
#       robot_base_frame: base_footprint

#       use_sim_time: true
#       resolution: 0.05
#       plugins:
#       - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
#       - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
#       - {name: static_layer, type: "costmap_2d::StaticLayer"}

# global_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint

#   footprint_padding: 0.03
#   update_frequency: 10.0
#   publish_frequency: 10.0
#   transform_tolerance: 0.5

#   use_sim_time: true
#   resolution: 0.05
#   plugins:
#     - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
#     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
#     - {name: static_layer, type: "costmap_2d::StaticLayer"}
  
#   obstacle_layer:
#     observation_sources: scan
#     scan: {sensor_frame: base_scan_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#   inflation_layer:
#     inflation_radius: 1.0      # 팽창 반경 (미터)
#     cost_scaling_factor: 3.0  # 팽창 코스트 스케일링 팩터

#   static_layer:
#     map_topic: map
#     subscribe_to_updates: true
