<?xml version="1.0"?>
<robot name="jms_robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Include the urdf/xacro file -->
    <xacro:include filename="$(find jms_simulation_robot)/urdf/macros.xacro" />
    <xacro:include filename="$(find jms_simulation_robot)/urdf/materials.xacro" />
    <xacro:include filename="$(find jms_simulation_robot)/urdf/robot_gazebo.urdf.xacro" />

    <!-- Robot Base footprint-->
    <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${base_height/2+wheel_zoff}" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- Robot base link-->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
            <material name="FFF6CE" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="0.108" w="${base_width}" d="${base_length}" h="${base_height}" />
    </link>

    <joint name="base_to_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-wheel_xoff} ${(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="left_wheel_link" >
        <visual>
            <origin xyz="0.0 0.0 0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="white" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="0.0007853" r="${wheel_radius}" h="${wheel_width}" />
    </link>

    <joint name="base_to_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${(-wheel_xoff)} ${-(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="right_wheel_link" >
        <visual>
            <origin xyz="0.0 0.0 0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="669966" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="0.007853" r="${wheel_radius}" h="${wheel_width}" />
    </link>


    <!-- <joint name="base_to_caster_joint" type="fixed"> -->
    <joint name="base_to_caster_joint" type="continuous">
        <parent link="base_link"/>
        <child link="caster_link"/>
        <origin xyz="${-base_length/2} 0 ${-wheel_zoff}" rpy="0 0 0"/>
        <!-- <origin xyz="${(-base_length/4)} 0 ${-(base_height/2)}" rpy="0 0 0"/> -->
        <!-- <origin xyz="${(wheel_xoff+base_length/4)} 0.0 ${-(base_height/2)}" rpy="0 0 0"/> -->
        <axis xyz="0 1 0"/>
    </joint>

    <!-- Caster Wheel -->
    <link name="caster_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="669966" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>

        <xacro:sphere_inertia m="0.000221" r="${caster_radius}"/>
    </link>


    <joint name="base_to_scan_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_scan_link"/>
        <origin xyz="0 0 ${(base_height/2 + lidar_height/4)}" rpy="0 0 0"/>        
        <axis xyz="0 0 1"/>
        <!-- <limit lower="${-pi}" upper="${pi}" effort="14.27" velocity="0.5"/> -->
    </joint>


    <link name="base_scan_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_radius}"/>
            </geometry>
            <material name="white" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="0.007853" r="${lidar_radius}" h="${lidar_height}" />
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="imu_link" />
</robot>