<?xml version="1.0"?>
<robot name="jms_robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Include the urdf/xacro file -->
    <xacro:include filename="$(find jms_simulation_robot)/urdf/macros.xacro" />
    <xacro:include filename="$(find jms_simulation_robot)/urdf/materials.xacro" />
    <xacro:include filename="$(find jms_simulation_robot)/urdf/robot_gazebo.urdf.xacro" />


    <!-- Robot Base footprint-->
    <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
        <origin xyz="0.0 0.0 ${(base_height/2 + wheel_zoff)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>

    <!-- Robot base link-->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
            <material name="FFF6CE" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="108.0" w="${base_width}" d="${base_length}" h="${base_height}" />
    </link>

    <link name="left_wheel_link" >
        <visual>
            <origin xyz="0.0 0.0 0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="669966" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="43.63" r="${wheel_radius}" h="${wheel_width}" />
    </link>

    <joint name="base_to_left_wheel_joint" type="continuous">
        <origin xyz="${(-wheel_xoff)} ${(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>


    <link name="right_wheel_link" >
        <visual>
            <origin xyz="0.0 0.0 0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="669966" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="43.63" r="${wheel_radius}" h="${wheel_width}" />
    </link>

    <joint name="base_to_right_wheel_joint" type="continuous">
        <origin xyz="${(-wheel_xoff)} ${-(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>


    <!-- Robot drive wheels link -->
    <!-- <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_link" >
            <visual>
                <origin xyz="0.0 0.0 0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="669966" />
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="43.63" r="${wheel_radius}" h="${wheel_width}" />

        </link>

        <joint that connect between base and wheels>
        <joint name="base_to_${prefix}_joint" type="continuous">
            <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_link"/>
            <axis xyz="0 1 0"/>
            <limit lower="${-pi}" upper="${pi}" effort="63.804" velocity="0.5"/>

        </joint>
    </xacro:macro>

    <xacro:wheel prefix="left_wheel" x_reflect="-1" y_reflect="1" />
    <xacro:wheel prefix="right_wheel" x_reflect="-1" y_reflect="-1" /> -->
 
    <!-- LiDAR(base_laser_link) setup-->
    

    <!-- Caster Wheel -->
    <link name="caster_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="669966" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>

        <xacro:sphere_inertia m="0.5" r="${caster_radius}"/>
    </link>

    <joint name="base_to_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_link"/>
        <origin xyz="${(wheel_xoff+base_length/4)} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
    </joint>

    <!-- <xacro:macro name="sick_lms1xx" params="frame" >
        <link name="${frame}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_radius}"/>
                </geometry>
                <material name="white" />
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="29.09" r="${lidar_radius}" h="${lidar_height}" />
        </link>

        <joint name="base_to_laser_joint" type="continuous">
            <origin xyz="${base_length/2 -lidar_radius*2} 0 ${(base_height/2+lidar_height/2)}" rpy="0 0 0"/>
            <origin xyz="0 0 ${(base_height/2 + lidar_height/4)}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="base_laser_link"/>
            <axis xyz="0 0 1"/>
            <limit lower="${-pi}" upper="${pi}" effort="14.27" velocity="0.5"/>
        </joint>
    </xacro:macro>
    <xacro:sick_lms1xx frame="base_laser_link" /> -->

    <link name="base_scan_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_radius}"/>
            </geometry>
            <material name="white" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="29.09" r="${lidar_radius}" h="${lidar_height}" />
    </link>

    <joint name="base_to_scan_joint" type="continuous">
        <origin xyz="0 0 ${(base_height/2 + lidar_height/4)}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="base_scan_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi}" upper="${pi}" effort="14.27" velocity="0.5"/>
    </joint>

</robot>
