<!-- <?xml version="1.0"?> -->
<!-- <robot name="jms_robot" xmlns:xacro="http://ros.org/wiki/xacro"> -->
    <!-- Robot drive wheels link -->
    <!-- <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_link" >
            <visual>
                <origin xyz="0.0 0.0 0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="669966" />
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="43.63" r="${wheel_radius}" h="${wheel_width}" />

        </link>

        <joint that connect between base and wheels>
        <joint name="base_to_${prefix}_joint" type="continuous">
            <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_link"/>
            <axis xyz="0 1 0"/>
            <limit lower="${-pi}" upper="${pi}" effort="63.804" velocity="0.5"/>

        </joint>
    </xacro:macro>

    <xacro:wheel prefix="left_wheel" x_reflect="-1" y_reflect="1" />
    <xacro:wheel prefix="right_wheel" x_reflect="-1" y_reflect="-1" /> -->
 
    <!-- LiDAR(base_laser_link) setup-->
    

    <!-- <xacro:macro name="sick_lms1xx" params="frame" >
        <link name="${frame}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_radius}"/>
                </geometry>
                <material name="white" />
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="29.09" r="${lidar_radius}" h="${lidar_height}" />
        </link>

        <joint name="base_to_laser_joint" type="continuous">
            <origin xyz="${base_length/2 -lidar_radius*2} 0 ${(base_height/2+lidar_height/2)}" rpy="0 0 0"/>
            <origin xyz="0 0 ${(base_height/2 + lidar_height/4)}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="base_laser_link"/>
            <axis xyz="0 0 1"/>
            <limit lower="${-pi}" upper="${pi}" effort="14.27" velocity="0.5"/>
        </joint>
    </xacro:macro>
    <xacro:sick_lms1xx frame="base_laser_link" /> -->
<!-- </robot> -->